[package]
name = "bin"
version = "0.1.0"
edition = "2021"
default-run = "bin"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = {path = "../core"}
tokio = {workspace = true}
salvo = {workspace = true}