[workspace]
members = [
  "bin",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
salvo = {version ="*", features = ["oapi"]}
serde = { version = "1", features = ["derive"] }
